#curl 'http://localhost:9000/init/install-edge.sh?group=default_fleet&token=criblmaster&user=cribl&install_dir=%2Fopt%2Fcribl-edge' | bash -
#find a way to run this from the leader at every startup...
version: '3.8'
services:
  master:
    image: cribl/cribl:4.3.0
    environment:
      - CRIBL_DIST_MODE=master
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@0.0.0.0:4200
    ports:
      - 19000:9000
  worker1:
    image: cribl/cribl:4.3.0
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    depends_on: 
      - master
    environment:
      - CRIBL_DIST_MODE=worker
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@master:4200?group=default
      - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
    ports:
      - 9000
    volumes:
      - part1:/opt/cribl/config-volume
  worker2:
    image: cribl/cribl:4.3.0
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    depends_on: 
      - master
    environment:
      - CRIBL_DIST_MODE=worker
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@master:4200?group=default
      - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
    ports:
      - 9000
    volumes:
      - part2:/opt/cribl/config-volume
  minio:
    image: minio/minio
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
    command: server --console-address ":9001" /data
volumes:
  part1:
    driver_opts:
      type: tmpfs
      o: "size=100m,nr_inodes=5000"
      device: tmpfs
  part2:
    driver_opts:
      type: tmpfs
      o: "size=100m,nr_inodes=5000"
      device: tmpfs
networks:
  default:
    name: elastic
    external: true
