version: '3.8'
services:
  cribl:
    image: cribl/cribl:4.5.1
    environment:
      CRIBL_DIST_MODE: single
      NODE_EXTRA_CA_CERTS: /opt/criblfiles/nginxcert.pem
      CRIBL_BEFORE_START_CMD_1: >
        mkdir -p /opt/cribl/local/cribl/pipelines/minio_to_sqs;
        mkdir -p /opt/cribl/local/cribl/auth;
        cp -r /tmp/workerconf/* /opt/cribl/local/cribl;
    ports:
      - 19000:9000
    volumes:
      - ./workerconf/:/tmp/workerconf
      - ./ssl/nginxcert.pem:/opt/criblfiles/nginxcert.pem
  minio:
    image: quay.io/minio/minio
    ports:
      - 9090:9000
      - 9001:9001
    container_name: minio
    environment:
      - MINIO_HTTP_TRACE=/tmp/minio.log
      - MINIO_NOTIFY_WEBHOOK_ENABLE_CRIBL=on
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT_CRIBL=http://cribl:9324
    command: server /data --console-address ":9001"
    depends_on:
      - elasticmq
  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
     /bin/sh -c "mc config &&
                 mc config host add myminio http://minio:9000 minioadmin minioadmin &&
                 mc mb myminio/test-bucket &&
                 mc event add --event \"put,get,delete,replica,ilm,scanner\" myminio/test-bucket arn:minio:sqs::CRIBL:webhook &&
                 echo \"my content\" > myfile.txt &&
                 /usr/bin/mc cp myfile.txt myminio/test-bucket &&
                 exit 0"
  elasticmq:
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./elasticmq/custom.conf:/opt/elasticmq.conf
    image: softwaremill/elasticmq-native
  #https://gcore.com/learning/reverse-proxy-with-docker-compose/
  #https://medium.com/geekculture/webapp-nginx-and-ssl-in-docker-compose-6d02bdbe8fa0
  #https://gist.github.com/dahlsailrunner/679e6dec5fd769f30bce90447ae80081
  #cribl > https > nginx:10080 > http > minio:9000
  #cribl > https > nginx:10081 > http > elasticmq:9324
  nginx:
    image: nginx
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/nginxkey.key:/etc/nginx/cert/nginxkey.key
      - ./ssl/nginxcert.crt:/etc/nginx/cert/nginxcert.crt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - cribl
      - minio
      - elasticmq
